package com.yitutech.dao;

import com.yitutech.model.Person;
import com.yitutech.model.PersonExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON
     *
     * @mbg.generated Thu Mar 22 11:45:44 CST 2018
     */
    long countByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON
     *
     * @mbg.generated Thu Mar 22 11:45:44 CST 2018
     */
    int deleteByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON
     *
     * @mbg.generated Thu Mar 22 11:45:44 CST 2018
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON
     *
     * @mbg.generated Thu Mar 22 11:45:44 CST 2018
     */
    int insertSelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON
     *
     * @mbg.generated Thu Mar 22 11:45:44 CST 2018
     */
    List<Person> selectByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON
     *
     * @mbg.generated Thu Mar 22 11:45:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON
     *
     * @mbg.generated Thu Mar 22 11:45:44 CST 2018
     */
    int updateByExample(@Param("record") Person record, @Param("example") PersonExample example);
}