package com.yitutech.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;

@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Person {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.ID
     *
     * @mbg.generated Thu Mar 22 11:45:44 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.NAME
     *
     * @mbg.generated Thu Mar 22 11:45:44 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.ID
     *
     * @return the value of PERSON.ID
     *
     * @mbg.generated Thu Mar 22 11:45:44 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.ID
     *
     * @param id the value for PERSON.ID
     *
     * @mbg.generated Thu Mar 22 11:45:44 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.NAME
     *
     * @return the value of PERSON.NAME
     *
     * @mbg.generated Thu Mar 22 11:45:44 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.NAME
     *
     * @param name the value for PERSON.NAME
     *
     * @mbg.generated Thu Mar 22 11:45:44 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}